### ISSUE TITLE
What's different between this and auto-value-moshi

### ISSUE THREAD

**Issue by nedtwigg** [PhilGlass/auto-moshi#1]
Hiya!  I'm a happy auto-value-moshi user, but the most recent version now generates [compile warnings](https://github.com/rharter/auto-value-moshi/issues/99) which are [difficult to fix](https://github.com/rharter/auto-value-moshi/pull/101).

> This library is heavily influenced by auto-value-moshi.

Just curious what's different in your approach that made you take the effort to build this?

**Comment by PhilGlass** [comment]
At the time there were a few reasons:
- There was no support for nested generics or package-private classes in auto-value-moshi.
- I had loads of small JSON models, and adding a static method returning a `JsonAdapter<T>` on each one added up to quite a lot of boilerplate.
- It was a good excuse to write some Kotlin & learn how the annotation processing API works!

I don't really use AutoValue any more though, so I don't have any plans to update this. It's definitely missing some features, like `@JsonQualifier` support.

**Comment by nedtwigg** [comment]
Awesome, thanks for the info!
